#Para mais detalhes sobre a imagem acessar: https://hub.docker.com.
services:
    rabbitmq:
        image: rabbitmq:4-management
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./dados:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=123456
